/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UploadImage': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'image-saved'; data: { originalFilename: string; uniqueFilename: string; format: string; originalStorageKey: string; originalUrl: string; traceId: string; uploadedAt: string } }>
    'MobileResize': EventHandler<{ originalFilename: string; uniqueFilename: string; format: string; originalStorageKey: string; originalUrl: string; traceId: string; uploadedAt: string }, { topic: 'mobile-resize-complete'; data: { originalFilename: string; uniqueFilename: string; format: string; originalStorageKey: string; originalUrl: string; traceId: string; uploadedAt: string; resizeType: string; outputStorageKey: string; outputUrl: string; completedAt: string } }>
    'LowQualityResize': EventHandler<{ originalFilename: string; uniqueFilename: string; format: string; originalStorageKey: string; originalUrl: string; traceId: string; uploadedAt: string }, { topic: 'lowquality-resize-complete'; data: { originalFilename: string; uniqueFilename: string; format: string; originalStorageKey: string; originalUrl: string; traceId: string; uploadedAt: string; resizeType: string; outputStorageKey: string; outputUrl: string; completedAt: string } }>
    'DesktopResize': EventHandler<{ originalFilename: string; uniqueFilename: string; format: string; originalStorageKey: string; originalUrl: string; traceId: string; uploadedAt: string }, { topic: 'desktop-resize-complete'; data: { originalFilename: string; uniqueFilename: string; format: string; originalStorageKey: string; originalUrl: string; traceId: string; uploadedAt: string; resizeType: string; outputStorageKey: string; outputUrl: string; completedAt: string } }>
    'CompletionTracker': EventHandler<{ originalFilename: string; uniqueFilename: string; format: string; originalStorageKey: string; originalUrl: string; traceId: string; uploadedAt: string; resizeType: string; outputStorageKey: string; outputUrl: string; completedAt: string }, never>
  }
}